#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
### bat as manpager
# export MANPAGER="bat -p"
# export BAT_THEME="TwoDark"
### lunarVim as manpager
export MANPAGER='lvim +Man!'
export MANWIDTH=999
# cargo
export PATH=$HOME/.cargo/bin:$PATH
# golang
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
# node
export PATH=$HOME/.fnm:$PATH
export PATH="$PATH:./node_modules/.bin"
eval "$(fnm env)"
# eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"
source "$HOME/.cargo/env"
export PATH=$HOME/.config/nvcode/utils/bin:$PATH
export PATH=$HOME/.config/nvcode/utils/bin:$PATH
. "$HOME/.cargo/env"
export PATH="$PATH:/usr/local/bin/Postman"
### Nvim as editor
export EDITOR='lvim'
export VISUAL='lvim'


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
        . "$HOME/.miniconda/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/.miniconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

